# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160222_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 2, 22, 9, 48, 35, 70878, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
